#FROM amazeeio/php:7.2-cli-drupal
FROM amazeeiodevelopment/denpal

#COPY composer2.json /app/
#RUN COMPOSER=composer2.json php composer.phar install
#RUN COMPOSER=composer2.json composer install
#RUN ./extra-packages.sh

#COPY . /app
#RUN /app/extra-packages.sh

COPY composer.json /app/
RUN rm -f /app/composer.lock
COPY scripts /app/scripts
RUN composer install --dev
COPY . /app

# Define where the Drupal Root is located
ENV WEBROOT=web
